/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import org.mariadb.jdbc.Connection;
import productosds.ConeccionDB;

/**
 *
 * @author val
 */
public class VentanaBuscarProductos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaListaProductos
     */
    public VentanaBuscarProductos() {
        setLocationRelativeTo(null);
        initComponents();
        try {
            // Crea un modelo de tabla por defecto, este modelo sirve para definir la estructura de una JTable
            DefaultTableModel modelo = new DefaultTableModel();

            // Establece el modelo recién creado a la tabla de usuarios (userTable)
            tabla.setModel(modelo); //nombre de la tabla

            // Declara las variables para preparar y ejecutar la consulta SQL
            PreparedStatement ps = null;
            ResultSet rs = null;

            // Crea un objeto de conexión a la base de datos usando la clase previamente definida: ConeccionDB
            ConeccionDB conn = new ConeccionDB();

            // Obtiene una conexión activa a la base de datos
            Connection con = conn.getConexion();

            // Definir la consulta SQL a ejecutar
            String sql = "SELECT * FROM productos";

            // Preparar la consulta SQL para su ejecución, esto ayuda a prevenir la inyección SQL
            ps = con.prepareStatement(sql);
            // Ejecuta la consulta y guarda el resultado en la variable rs

            rs = ps.executeQuery();

            // Obtiene metadatos del resultado, como número de columnas, nombres de columnas, etc.
            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            // Obtiene la cantidad de columnas del resultado
            int cantidadColumnas = rsMd.getColumnCount();

            // Define las columnas para el modelo de la JTable
            modelo.addColumn("Código");
            modelo.addColumn("Nombre");
            modelo.addColumn("Precio");
            modelo.addColumn("Distribuidor");
            modelo.addColumn("Categoria");

            // Define los anchos de las columnas em la tabla
            int[] anchos = {80, 220, 120, 150, 120};
            for (int i = 0; i < tabla.getColumnCount(); i++) {
                // Establece el ancho de cada columna
                tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            // El while se ejecuta mientras existan registros en la base de datos, pinta la información en la tabla
            while (rs.next()) {
                // Crea un array para guardar los valores de las columnas de un registro
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    // Obtiene el objeto de la columna i+1 (los indices en rs empiezan en 1, no en 0) y lo guarda en el array
                    filas[i] = rs.getObject(i + 1);

                }
                modelo.addRow(filas);
            }

            // Si ocurre algún errr SQL durante la ejecución del bloque try, entra en el bloque catch    
        } catch (SQLException ex) {
            System.err.print(ex.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        distribuidor = new javax.swing.JLabel();
        categoria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        codigo1 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        btnRegresar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnRegresar.setText("regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Código:");

        btnBuscar.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        btnBuscar.setText("buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Código:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Nombre:");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Precio:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Distribuidor:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Categoría:");

        codigo.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        codigo.setForeground(new java.awt.Color(51, 51, 51));
        codigo.setText(" ");
        codigo.setBorder(new javax.swing.border.MatteBorder(null));

        nombre.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        nombre.setForeground(new java.awt.Color(51, 51, 51));
        nombre.setText(" ");
        nombre.setBorder(new javax.swing.border.MatteBorder(null));

        precio.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        precio.setForeground(new java.awt.Color(51, 51, 51));
        precio.setText(" ");
        precio.setBorder(new javax.swing.border.MatteBorder(null));

        distribuidor.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        distribuidor.setForeground(new java.awt.Color(51, 51, 51));
        distribuidor.setText(" ");
        distribuidor.setBorder(new javax.swing.border.MatteBorder(null));

        categoria.setFont(new java.awt.Font("Dialog", 0, 17)); // NOI18N
        categoria.setForeground(new java.awt.Color(51, 51, 51));
        categoria.setText(" ");
        categoria.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("LISTA DE PRODUCTOS");

        codigo1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        codigo1.setForeground(new java.awt.Color(102, 102, 102));
        codigo1.setText("Seleccione un elemento de la tabla para conocer sus detalles");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnRegresar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(distribuidor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnBuscar)))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(codigo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(280, 280, 280))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigo)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(precio)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(distribuidor)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(categoria)
                            .addComponent(jLabel7))
                        .addGap(41, 41, 41)))
                .addComponent(codigo1)
                .addGap(18, 30, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal ventana = new VentanaPrincipal();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:

        String campo = txtCodigo.getText();
        String where = "";

        if (!"".equals(campo)) {
            where = " WHERE codigo = '" + campo + "'";

        }

        try {
            // Crea un modelo de tabla por defecto, este modelo sirve para definir la estructura de una JTable
            DefaultTableModel modelo = new DefaultTableModel();

            // Establece el modelo recién creado a la tabla de usuarios (userTable)
            tabla.setModel(modelo); //nombre de la tabla

            // Declara las variables para preparar y ejecutar la consulta SQL
            PreparedStatement ps = null;
            ResultSet rs = null;

            // Crea un objeto de conexión a la base de datos usando la clase previamente definida: ConeccionDB
            ConeccionDB conn = new ConeccionDB();

            // Obtiene una conexión activa a la base de datos
            Connection con = conn.getConexion();

            // Definir la consulta SQL a ejecutar
            String sql = "SELECT * FROM productos" + where;

            // Preparar la consulta SQL para su ejecución, esto ayuda a prevenir la inyección SQL
            ps = con.prepareStatement(sql);
            // Ejecuta la consulta y guarda el resultado en la variable rs

            rs = ps.executeQuery();

            // Obtiene metadatos del resultado, como número de columnas, nombres de columnas, etc.
            ResultSetMetaData rsMd = (ResultSetMetaData) rs.getMetaData();
            // Obtiene la cantidad de columnas del resultado
            int cantidadColumnas = rsMd.getColumnCount();

            // Define las columnas para el modelo de la JTable
            modelo.addColumn("Código");
            modelo.addColumn("Nombre");
            modelo.addColumn("Precio");
            modelo.addColumn("Distribuidor");
            modelo.addColumn("Categoria");

            // Define los anchos de las columnas em la tabla
            int[] anchos = {80, 220, 120, 150, 120};
            for (int i = 0; i < tabla.getColumnCount(); i++) {
                // Establece el ancho de cada columna
                tabla.getColumnModel().getColumn(i).setPreferredWidth(anchos[i]);
            }

            // El while se ejecuta mientras existan registros en la base de datos, pinta la información en la tabla
            while (rs.next()) {
                // Crea un array para guardar los valores de las columnas de un registro
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    // Obtiene el objeto de la columna i+1 (los indices en rs empiezan en 1, no en 0) y lo guarda en el array
                    filas[i] = rs.getObject(i + 1);

                }
                modelo.addRow(filas);
            }

            // Si ocurre algún errr SQL durante la ejecución del bloque try, entra en el bloque catch    
        } catch (SQLException ex) {
            System.err.print(ex.toString());
        }


    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        // TODO add your handling code here:
        int seleccionado = tabla.getSelectedRow();

        codigo.setText(tabla.getValueAt(seleccionado, 0).toString());
        nombre.setText(tabla.getValueAt(seleccionado, 1).toString());
        precio.setText(tabla.getValueAt(seleccionado, 2).toString());
        distribuidor.setText(tabla.getValueAt(seleccionado, 3).toString());
        categoria.setText(tabla.getValueAt(seleccionado, 4).toString());
    }//GEN-LAST:event_tablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBuscarProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel categoria;
    private javax.swing.JLabel codigo;
    private javax.swing.JLabel codigo1;
    private javax.swing.JLabel distribuidor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombre;
    private javax.swing.JLabel precio;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
